name: AI Proxy
on:
  push:
    paths:
      - "query.txt"
jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Test
        run: echo "hello world"